// <auto-generated />
using EntityFrameworkExample.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EntityFrameworkExample.Migrations;

[DbContext(typeof(PersonContext))]
[Migration("20240513165536_InitialCreate")]
partial class InitialCreate
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder.HasAnnotation("ProductVersion", "8.0.4");

        modelBuilder.Entity("EntityFrameworkExample.Models.Person", b =>
            {
                b.Property<int>("PersonId")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<string>("Address")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<string>("City")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<string>("FirstName")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<string>("LastName")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.HasKey("PersonId");

                b.ToTable("People");

                b.HasData(
                    new
                    {
                        PersonId = 1,
                        Address = "317 Long Street",
                        City = "Ocala",
                        FirstName = "Tara",
                        LastName = "Brewer"
                    },
                    new
                    {
                        PersonId = 2,
                        Address = "3163 Nickel Road",
                        City = "Anaheim",
                        FirstName = "Andrew",
                        LastName = "Tippett"
                    });
            });
#pragma warning restore 612, 618
    }
}
